github:
  description: "Testing infrastructure for Apache Pulsar"
  homepage: https://pulsar.apache.org/
  labels:
    - pulsar
    - pubsub
    - test-infra
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issues management
    issues: true
    # Enable projects for project management boards
    projects: true
  enabled_merge_buttons:
    # enable squash button:
    squash:  true
    # disable merge button:
    merge:   false
    # disable rebase button:
    rebase:  false